
spring:
  application:
    name: chats
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.1.13:3306/chats?characterEncoding=utf8
  data:
    redis:
      host: 192.168.1.13
      password: 1234

# websocket 服务端口
ws-port: 8060
server:
  servlet:
    context-path: /chats
